[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "*"
derive_more = "*"
derive-new = "*"
env_logger = "*"
grid = "*"
indicatif = {version = "*", optional=true}
itertools = "*"
log = "*"
num = "*"
test-log = "*"
strum = { version = "*", features = ["derive"] }

[features]
default = ["progressbar"]
progressbar = ["dep:indicatif"]

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"