[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = {version = "*", optional=true}
num = "*"
grid = "*"
log = "*"
env_logger = "*"
test-log = "*"
itertools = "*"

[features]
default = ["progressbar"]
progressbar = ["dep:indicatif"]
